"""
ClaimShield AI — Responsible AI & Governance View.
"""

from __future__ import annotations

import streamlit as st
from ui.views.common import (
    render_clean_html,
    render_html,
    icon_md,
    SMART_TOY,
)


def render_responsible_ai_page():
    """Renders Responsible AI, ethics, transparency, and data governance documentation."""
    st.markdown(f"### {icon_md(SMART_TOY)} Responsible AI — Ethics, Transparency & Data Protection")
    st.markdown("ClaimShield AI is built with Responsible AI principles at its core. This section documents how our system addresses fairness, explainability, transparency, and user data protection.")

    rai1, rai2 = st.columns(2)

    with rai1:
        render_html("""
        <div class='glass-card' style='border-left: 5px solid #059669;'>
            <div style='display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; flex-wrap: wrap; gap: 8px;'>
                <h4 style='color: #059669; margin: 0; font-size: 1.15em;'><span class="material-symbols-rounded">search</span> Transparency & Auditability</h4>
                <span class='verdict-badge' style='background: rgba(16, 185, 129, 0.15); color: #047857; border: 1px solid rgba(16, 185, 129, 0.35); font-size: 0.74em;'>
                    <span class="material-symbols-rounded">check_circle</span> Fully Traceable
                </span>
            </div>
            <p style='color: #475569; font-size: 0.9em; line-height: 1.6; margin-bottom: 12px;'>
                Every verification decision is completely auditable and end-to-end inspectable:
            </p>
            <ul style='color: #334155; line-height: 1.8; font-size: 0.9em; padding-left: 20px; margin-bottom: 0;'>
                <li>Complete agent-to-agent communication logs (A2A/1.0 protocol)</li>
                <li>Retrieved source articles with cosine similarity scores & URLs</li>
                <li>The exact LLM prompt and processing engine used</li>
                <li>NER entities and search queries derived from claims</li>
                <li>Extractive evidence summaries generated by the NLP pipeline</li>
            </ul>
        </div>
        """)

        render_html("""
        <div class='glass-card' style='border-left: 5px solid #D97706;'>
            <div style='display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; flex-wrap: wrap; gap: 8px;'>
                <h4 style='color: #D97706; margin: 0; font-size: 1.15em;'><span class="material-symbols-rounded">balance</span> Algorithmic Fairness</h4>
                <span class='verdict-badge' style='background: rgba(245, 158, 11, 0.15); color: #B45309; border: 1px solid rgba(245, 158, 11, 0.35); font-size: 0.74em;'>
                    <span class="material-symbols-rounded">balance</span> Uniform Verification
                </span>
            </div>
            <p style='color: #334155; line-height: 1.65; font-size: 0.9em; margin-bottom: 0;'>
                ClaimShield applies the <strong>same verification pipeline</strong> to all users regardless of subscription tier.
                Commercial plans differ only by request capacity and display depth (Free: 3 capacity displaying 2 resources; Pro: unlimited displaying 3–5 resources), but the NLP analysis,
                FAISS retrieval algorithm, and LLM verification logic are strictly identical for every query.
                No user demographic data influences the fact-checking verdict.
            </p>
        </div>
        """)

        render_html("""
        <div class='glass-card' style='border-left: 5px solid #4F46E5;'>
            <div style='display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; flex-wrap: wrap; gap: 8px;'>
                <h4 style='color: #4F46E5; margin: 0; font-size: 1.15em;'><span class="material-symbols-rounded">psychology</span> Grounding & Bias Mitigation</h4>
                <span class='verdict-badge' style='background: rgba(79, 70, 229, 0.15); color: #4338CA; border: 1px solid rgba(79, 70, 229, 0.35); font-size: 0.74em;'>
                    <span class="material-symbols-rounded">shield</span> Multi-LLM Consensus
                </span>
            </div>
            <p style='color: #475569; font-size: 0.9em; line-height: 1.6; margin-bottom: 12px;'>
                To systematically eliminate cognitive and model bias in verification outcomes:
            </p>
            <ul style='color: #334155; line-height: 1.8; font-size: 0.9em; padding-left: 20px; margin-bottom: 0;'>
                <li>The LLM is <strong>grounded in retrieved evidence</strong> — verdicts must cite specific article quotes rather than unverified pre-trained memory</li>
                <li>Multi-source retrieval ensures diverse, authoritative perspectives are considered</li>
                <li>Confidence metrics mathematically quantify certainty, preventing overconfident claims</li>
                <li>Categorical classification (Supported/Contradicted/Unclear) avoids binary bias</li>
            </ul>
        </div>
        """)

    with rai2:
        render_html("""
        <div class='glass-card' style='border-left: 5px solid #7C3AED;'>
            <div style='display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; flex-wrap: wrap; gap: 8px;'>
                <h4 style='color: #7C3AED; margin: 0; font-size: 1.15em;'><span class="material-symbols-rounded">lightbulb</span> Multi-Layer Explainability</h4>
                <span class='verdict-badge' style='background: rgba(124, 58, 237, 0.15); color: #6D28D9; border: 1px solid rgba(124, 58, 237, 0.35); font-size: 0.74em;'>
                    <span class="material-symbols-rounded">menu_book</span> Transparent Rationale
                </span>
            </div>
            <p style='color: #475569; font-size: 0.9em; line-height: 1.6; margin-bottom: 12px;'>
                Every fact-check verdict generated by ClaimShield AI includes complete transparency attributes:
            </p>
            <ul style='color: #334155; line-height: 1.8; font-size: 0.9em; padding-left: 20px; margin-bottom: 0;'>
                <li><strong>Categorical Verdict</strong> — Supported, Contradicted, Direct Answer, or Unclear</li>
                <li><strong>Confidence Score</strong> — Quantified probabilistic certainty (0–100%)</li>
                <li><strong>Summary Reasoning</strong> — Multi-sentence explanation of the verdict rationale</li>
                <li><strong>Inline Citations</strong> — Exact verbatim quotes from verified source articles</li>
                <li><strong>Named Entities</strong> — spaCy NER extractions showing concepts parsed by AI</li>
                <li><strong>Extractive Evidence Highlights</strong> — Key supporting statements synthesized</li>
            </ul>
        </div>
        """)

        render_html("""
        <div class='glass-card' style='border-left: 5px solid #DC2626;'>
            <div style='display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; flex-wrap: wrap; gap: 8px;'>
                <h4 style='color: #DC2626; margin: 0; font-size: 1.15em;'><span class="material-symbols-rounded">lock</span> Cryptographic Security</h4>
                <span class='verdict-badge' style='background: rgba(239, 68, 68, 0.15); color: #B91C1C; border: 1px solid rgba(239, 68, 68, 0.35); font-size: 0.74em;'>
                    <span class="material-symbols-rounded">shield</span> Defense in Depth
                </span>
            </div>
            <p style='color: #475569; font-size: 0.9em; line-height: 1.6; margin-bottom: 12px;'>
                User session and telemetry data are safeguarded through multi-layered defenses:
            </p>
            <ul style='color: #334155; line-height: 1.8; font-size: 0.9em; padding-left: 20px; margin-bottom: 0;'>
                <li><strong>Password Hashing</strong> — PBKDF2-SHA256 with random salt (100,000 iterations)</li>
                <li><strong>Session Tokens</strong> — Signed JWT (HS256) with 60-minute automated expiry</li>
                <li><strong>Encryption at Rest</strong> — Fernet symmetric AES encryption for audit log payloads</li>
                <li><strong>Input Sanitization</strong> — XSS, HTML, and script injection stripping with length bounds</li>
                <li><strong>Rate Limiting</strong> — Token-bucket capacity enforcement prevents API denial-of-service</li>
            </ul>
        </div>
        """)

        render_html("""
        <div class='glass-card' style='border-left: 5px solid #0284C7;'>
            <div style='display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; flex-wrap: wrap; gap: 8px;'>
                <h4 style='color: #0284C7; margin: 0; font-size: 1.15em;'><span class="material-symbols-rounded">person</span> User Data Rights & Privacy</h4>
                <span class='verdict-badge' style='background: rgba(2, 132, 199, 0.15); color: #0369A1; border: 1px solid rgba(2, 132, 199, 0.35); font-size: 0.74em;'>
                    <span class="material-symbols-rounded">assignment</span> Privacy Protected
                </span>
            </div>
            <p style='color: #475569; font-size: 0.9em; line-height: 1.6; margin-bottom: 12px;'>
                In strict alignment with ethical data governance principles:
            </p>
            <ul style='color: #334155; line-height: 1.8; font-size: 0.9em; padding-left: 20px; margin-bottom: 0;'>
                <li>Users retain full visibility into their verification history via encrypted audit logs</li>
                <li>All personal data is persisted in private storage (SQLite local / Supabase cloud)</li>
                <li>Zero user telemetry is commercialized or sold to third-party data brokers</li>
                <li>Users may update credentials or request purge of verification logs at any time</li>
            </ul>
        </div>
        """)

    render_html("""
    <div class='glass-card' style='border: 1px solid rgba(5, 150, 105, 0.40); background: var(--glass-surface-tint-success); text-align: center; padding: 28px 24px; margin-top: 10px;'>
        <div style='display: inline-flex; align-items: center; justify-content: center; width: 44px; height: 44px; border-radius: 50%; background: linear-gradient(135deg, #059669, #047857); color: white; font-size: 1.3em; margin-bottom: 10px; box-shadow: 0 4px 14px rgba(5,150,105,0.25);'>
            <span class="material-symbols-rounded">public</span>
        </div>
        <h3 style='color: #065F46; font-size: 1.3em; margin: 0 0 8px 0;'>Responsible AI Commitment</h3>
        <p style='color: #047857; font-size: 0.95em; line-height: 1.65; max-width: 780px; margin: 0 auto;'>
            ClaimShield AI is built from the ground up for ethical, evidence-based verification. We prioritize human editorial oversight,
            transparent provenance, and algorithmic integrity. Our multi-agent system empowers human judgment — it never supplants it.
        </p>
    </div>
    """)
